export default {
  vueI18n: {
    legacy: false,
    locale: "en",
    messages: {
      en: {
        welcome: "Welcome to Read_Book",
        name: "Name",
        email: "Email",
        login: "login",
        password: "Password",
        signSucc: "You have succesfully signed in!",
        signError: "Please enter valid email and password",
        passError:
          "Passwords must be at least 6 characters or your passwords dont match",
        logOut: "Logout",
        services: "Services",
        dashboard: "Dashboard",
        notRegistered: "Not Registered?",
        bookList: "List of Books",
        addNewBook: "Add New Book",
        save: "Save",
        book: "Book",
        bookName: "Book Name",
        bookGenre: "Book Genre",
        bookSize: "Book Size",
        myAccount: "My Account",
        allBooks: "All Books",
        readBooks: "Read Books",
        readPages: "Read Pages",
        bookReview: "Book Review",
        bookRating: "Book Rating",
        yourReview: "Your Review",
        yourRating: "Your Rating",
        sendReview: "Send Review",
        back: "Back",
        twitter: "Share on Twiiter",
        filterName: "Filter by Name",
        filterGenre: "Filter by Genre",
        filterSize: "Filter by Size",
        filterPages: "Filter by Read Pages",
        historyBooks: "History of books read",
        stars: "stars",
        settings: "Settings",
      },
      de: {
        welcome: "Willkommen bei Read_Book",
        name: "Name",
        email: "Email",
        login: "Anmeldung",
        password: "Passwort",
        signSucc: "Sie haben sich erfolgreich angemeldet!",
        signError:
          "Bitte geben Sie eine gültige E-Mail-Adresse und ein gültiges Passwort ein",
        passError:
          "Passwörter müssen mindestens 6 Zeichen lang sein, sonst stimmen Ihre Passwörter nicht überein",
        logOut: "Logout",
        home: "Heim",
        book: "Buch",
        services: "Dienstleistungen",
        dashboard: "Dashboard",
        notRegistered: "Nicht registriert?",
        addNewBook: "Neues Buch hinzufügen",
        save: "Speichern",
        bookName: "Buchname",
        bookGenre: "Buchgenre",
        bookSize: "Buchgröße",
        myAccount: "Mein Konto",
        allBooks: "Alle Bücher",
        readBooks: "Bücher lesen",
        readPages: "Seiten lesen",
        bookList: "Liste der Bücher",
        back: "Zurück",
        bookReview: "Buchrezension",
        bookRating: "Buchbewertung",
        yourReview: "Deine Bewertung",
        yourRating: "Deine Bewertung",
        sendReview: "Bewertung senden",
        twitter: "Auf Twiiter teilen",
        filterName: "Nach Name filt.",
        filterGenre: "Nach Genre filt.",
        filterSize: "Nach Größe filt.",
        filterPages: "Filt. Sie nach geles.Seit.",
        historyBooks: "Geschichte der gelesenen Bücher",
        stars: "Sterne",
        settings: "Einstellungen",
      },
      es: {
        welcome: "Bienvenido a Read_Book",
        name: "Nombre",
        email: "Email",
        login: "login",
        password: "Contraseña",
        signSucc: "¡Has iniciado sesión correctamente!",
        signError:
          "Por favor introduce un correo electrónico y una contraseña válidos",
        passError:
          "Las contraseñas deben tener al menos 6 caracteres o sus contraseñas no coinciden",
        logOut: "Logout",
        home: "Home",
        services: "Servicios",
        dashboard: "Dashboard",
        notRegistered: "¿No registrado?",
        save: "Guardar",
        book: "Libro",
        bookName: "Nombre del Libro",
        bookGenre: "Género del Libro",
        bookSize: "Tamaño del Libro",
        myAccount: "Mi Cuenta",
        allBooks: "Todos los Libros",
        readBooks: "Libros Leidos",
        readPages: "Páginas Leidas",
        bookList: "Lista de libros",
        addNewBook: "Agregar nuevo libro",
        back: "Atrás",
        bookReview: "Reseña del libro",
        bookRating: "Calificación del libro",
        yourReview: "Tu reseña",
        yourRating: "Tu clasificación",
        sendReview: "Enviar reseña",
        twitter: "Compartir en Twitter",
        filterName: "Filtr.por Nombre",
        filterGenre: "Filtr.por Género",
        filterSize: "Filtr.por Tamaño",
        filterPages: "Filtr.por Pág.Leídas",
        historyBooks: "Historia de los libros leídos.",
        stars: "estrellas",
        settings: "Ajustes",
      },
      uk: {
        welcome: "Ласкаво просимо до Read_Book",
        name: "Ім'я",
        email: "Електронна пошта",
        login: "логін",
        password: "Пароль",
        signSucc: "Ви успішно ввійшли!",
        signError: "Введіть дійсну адресу електронної пошти та пароль",
        passError:
          "Паролі повинні містити принаймні 6 символів, інакше ваші паролі не збігаються",
        logOut: "Вийти",
        services: "Послуги",
        dashboard: "Панель Приладів",
        notRegistered: "Не зареєстрований?",
        save: "Зберегти",
        book: "Книга",
        bookName: "Назва Книги",
        bookGenre: "Жанр Книги",
        bookSize: "Розмір Книги",
        myAccount: "Мій Рахунок",
        allBooks: "Всі Книги",
        readBooks: "Прочитані Книги",
        readPages: "Прочитані Сторінки",
        bookList: "Список книг",
        addNewBook: "Додати нову книгу",
        back: "Назад",
        bookReview: "Рецензія на книгу",
        bookRating: "Книжковий рейтинг",
        yourReview: "Ваш відгук",
        yourRating: "Ваш рейтинг",
        sendReview: "Відправити відгук",
        twitter: "Поділіться в Twitter",
        filterName: "Фільтрувати за назвою",
        filterGenre: "Фільтр. за жанром",
        filterSize: "Фільтр. за розміром",
        filterPages: "Фільтр. за прочит.стор.",
        historyBooks: "Історія прочитаних книг",
        stars: "зірки",
        settings: "Налаштування",
      },
      ru: {
        welcome: "Добро пожаловать в Read_Book",
        name: "Имя",
        email: "Почтовый адрес",
        login: "Логин",
        password: "Пароль",
        signSucc: "Вы успешно авторизованы!",
        signError: "Пожалуйста, введите правильный почтовый адрес и пароль",
        passError:
          "Пароль должен состоять из 6 знаков или ваши пароли не совпадают",
        logOut: "Выйти",
        home: "Домашняя страница",
        aboutUs: "О нас",
        book: "Книга",
        faq: "FAQ",
        contact: "Контакты",
        dashboard: "Панель управления",
        notRegistered: "Не зарегистрирован?",
        services: "Сервисы",
        bookList: "Список Книг",
        addNewBook: "Добавить Новую Книгу",
        save: "Сохранить",
        bookName: "Название Книги",
        bookGenre: "Жанр Книги",
        bookSize: "Размер Книги",
        myAccount: "Мой Аккаунт",
        allBooks: "Все Книги",
        readBooks: "Прочитанные Книги",
        readPages: "Прочитанные Страницы",
        back: "Назад",
        bookReview: "Рецензия на книгу",
        bookRating: "Рейтинг книги",
        yourReview: "Ваш обзор",
        yourRating: "Ваш рейтинг",
        sendReview: "Отправить отзыв",
        twitter: "Поделиться в Twitter",
        filterName: "Фильтр. по назван.",
        filterGenre: "Фильтр. по жанру",
        filterSize: "Фильтр. по размеру",
        filterPages: "Фильтр.по прочит.стр.",
        historyBooks: "История прочитаних книг",
        stars: "звезды",
        settings: "Настройки",
      },
      az: {
        welcome: "Read_Book-a xoş gəlmisiniz",
        name: "Ad",
        email: "Email",
        login: "Login",
        password: "Parol",
        signSucc: "Siz uğurla daxil oldunuz!",
        signError: "Zəhmət olmasa etibarlı e-poçt və parol daxil edin",
        passError:
          "Parollar ən azı 6 simvoldan ibarət olmalıdır və ya parollarınız uyğun gəlmir",
        logOut: "Çıxış",
        aboutUs: "Bizim Haqqımızda",
        dashboard: "İdarə paneli",
        notRegistered: "Qeydiyyatdan keçməmisiniz?",
        services: "Xidmətlər",
        book: "Kitab",
        bookList: "Kitabların Siyahısı",
        addNewBook: "Yeni Kitab Əlavə Etmək",
        save: "Yadda Saxla",
        bookName: "Kitab Adı",
        bookGenre: "Kitab Janrı",
        bookSize: "Kitab ölçüsü",
        myAccount: "Mənim Hesabım",
        allBooks: "Bütün Kitablar",
        readBooks: "Oxuduğum Kitablar",
        readPages: "Oxuduğum Səhifələr",
        back: "Geri",
        bookReview: "Kitab icmalı",
        bookRating: "Kitab reytinqi",
        yourReview: "Rəyiniz",
        yourRating: "Reytinqiniz",
        sendReview: "Rəy göndər",
        twitter: "Twiiter-də paylaş",
        filterName: "Ada görə filtr",
        filterGenre: "Janr üzrə filtr",
        filterSize: "Ölçüyə görə filtr",
        filterPages: "Oxuma Səhif. görə filtr",
        historyBooks: "Oxunan kitabların tarixi",
        stars: "ulduzlar",
        settings: "Parametrlər",
      },
      tr: {
        welcome: "Read_Book'a hoş geldiniz",
        name: "Isim",
        email: "E-posta",
        login: "login",
        password: "Şifre",
        signSucc: "Başarıyla oturum açtınız!",
        signError: "Lütfen geçerli bir e-posta ve şifre girin",
        passError:
          "Şifreler en az 6 karakter olmalı, aksi takdirde şifreleriniz eşleşmiyor",
        logOut: "Çıkış Yap",
        dashboard: "Gösterge Paneli",
        notRegistered: "Kayıtlı değil?",
        services: "Hizmetler",
        book: "Kitap",
        bookList: "Kitap Listesi",
        addNewBook: "Yeni Kitap Ekle",
        save: "Kaydetmek",
        bookName: "Kitap Adı",
        bookGenre: "Kitap Türü",
        bookSize: "Kitap Boyutu",
        myAccount: "Hesabım",
        allBooks: "Tüm Kitaplar",
        readBooks: "Okuduğum Kitaplar",
        readPages: "Okuduğum Sayfalar",
        back: "Geri",
        bookReview: "Kitap incelemesi",
        bookRating: "Book Rating",
        yourReview: "Kitap Değerlendirmesi",
        yourRating: "Sizin dereceniz",
        sendReview: "İnceleme Gönder",
        twitter: "Twiiter'da Paylaş",
        filterName: "İsme Göre Filtr.",
        filterGenre: "Türe göre filtr.",
        filterSize: "Boyuta Göre Filt.",
        filterPages: "Okuma Sayf.Göre Filtr.",
        historyBooks: "Okunan kitapların tarihi",
        stars: "yıldızlar",
        settings: "Ayarlar",
      },
    },
  },
  locales: ["en", "de", "es", "ru", "tr", "az", "uk"],
  defaultLocale: "en",
};
