export default {
  vueI18n: {
    legacy: false,
    locale: "en",
    messages: {
      en: {
        welcome: "Welcome to to Read_Book",
        name: "Name",
        email: "Email",
        login: "login",
        password: "Password",
        signSucc: "You have succesfully signed in!",
        signError: "Please enter valid email and password",
        passError:
          "Passwords must be at least 6 characters or your passwords dont match",
        logOut: "Logout",
        home: "Home",
        aboutUs: "About Us",
        faq: "FAQ",
        contact: "Contact",
        services: "Services",
        dashboard: "Dashboard",
        notRegistered: "Not Registered?",
        bookList: "List of Books",
        addNewBook: "Add New Book",
        save: "Save",
        bookName: "Book Name",
        bookGenre: "Book Genre",
        bookSize: "Book Size",
        myAccount: "My Account",
      },
      de: {
        welcome: "Welcome to to Read_Book",
        name: "Name",
        email: "Email",
        login: "login",
        password: "Password",
        signSucc: "You have succesfully signed in!",
        signError: "Please enter valid email and password",
        passError:
          "Passwords must be at least 6 characters or your passwords dont match",
        logOut: "Logout",
        home: "Home",
        aboutUs: "About Us",
        faq: "FAQ",
        contact: "Contact",
        services: "Services",
        dashboard: "Dashboard",
        notRegistered: "Not Registered?"
      },
      es: {
        welcome: "Welcome to to Wes-Con Warehouse",
        name: "Name",
        email: "Email",
        login: "login",
        password: "Password",
        signSucc: "You have succesfully signed in!",
        signError: "Please enter valid email and password",
        passError:
          "Passwords must be at least 6 characters or your passwords dont match",
        logOut: "Logout",
        home: "Home",
        aboutUs: "About Us",
        faq: "FAQ",
        contact: "Contact",
        services: "Services",
        dashboard: "Dashboard",
        notRegistered: "Not Registered?"
      },
      ucr: {
        welcome: "Welcome to to Wes-Con Warehouse",
        name: "Name",
        email: "Email",
        login: "login",
        password: "Password",
        signSucc: "You have succesfully signed in!",
        signError: "Please enter valid email and password",
        passError:
          "Passwords must be at least 6 characters or your passwords dont match",
        logOut: "Logout",
        home: "Home",
        aboutUs: "About Us",
        faq: "FAQ",
        contact: "Contact",
        services: "Services",
        dashboard: "Dashboard",
        notRegistered: "Not Registered?"
      },
      ru: {
        welcome: "Welcome to to Wes-Con Warehouse",
        name: "Имя",
        email: "Почтовый адрес",
        login: "Логин",
        password: "Пароль",
        signSucc: "Вы успешно авторизованы!",
        signError: "Пожалуйста, введите правильный почтовый адрес и пароль",
        passError:
          "Пароль должен состоять из 6 знаков или ваши пароли не совпадают",
        logOut: "Выйти",
        home: "Домашняя страница",
        aboutUs: "О нас",
        faq: "FAQ",
        contact: "Контакты",
        dashboard: "Панель управления",
        notRegistered: "Not Registered?"
      },
      az: {
        welcome: "Welcome to to Wes-Con Warehouse",
        name: "Ad",
        email: "Email",
        login: "Login",
        password: "Parol",
        signSucc: "Siz uğurla daxil oldunuz!",
        signError: "Zəhmət olmasa etibarlı e-poçt və parol daxil edin",
        passError:
          "Parollar ən azı 6 simvoldan ibarət olmalıdır və ya parollarınız uyğun gəlmir",
        logOut: "Çıxış",
        home: "Ev",
        aboutUs: "Bizim haqqımızda",
        faq: "FAQ",
        contact: "Əlaqə",
        dashboard: "İdarə paneli",
        notRegistered: "Not Registered?"
      },
      tr: {
        welcome: "Welcome to Read_Book",
        name: "Isim",
        email: "E-posta",
        login: "login",
        password: "Şifre",
        signSucc: "Başarıyla oturum açtınız!",
        signError: "Lütfen geçerli bir e-posta ve şifre girin",
        passError:
          "Şifreler en az 6 karakter olmalı, aksi takdirde şifreleriniz eşleşmiyor",
        logOut: "Logout",
        home: "Ev",
        aboutUs: "Hakkımızda",
        faq: "FAQ",
        contact: "Temas etmek",
        dashboard: "Gösterge Paneli",
        notRegistered: "Not Registered?"
      },
    },
  },
  locales: ["en", "de", "es", "ru", "tr", "az", "ucr"],
  defaultLocale: "en",
};